// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:cc53d0ab-d6bc-4d87-a772-63527aecffa2',
    'aws_cognito_region': 'us-east-1',
    'aws_mandatory_sign_in': 'enable',
    'aws_project_region': 'us-east-1',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'olak-userfiles-5a1879daf38e',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_qpuiFOsRa',
    'aws_user_pools_mfa_type': 'OPTIONAL',
    'aws_user_pools_web_client_id': '26bvq94g749bcnf0g1q3poiakg',
    'aws_cloud_logic': 'enable',
    // 'aws_cloud_logic_custom': [{
    //     'name': 'ApiGateway',
    //     'endpoint': 'https://graphql.olakd.com',
    //     'region': 'us-east-1'
    // }],
};

export default awsmobile;
